### ISSUE TITLE
Develop branch - saving a graph resets values!

### ISSUE THREAD

**Issue by BryceBubbles** [HungryProton/concept_graph#73] opened 2020-06-07 13:46 UTC
Save a graph, close scene, reopen scene - all scalar and vector values are reset to default.

Was going to PR those noise and heightmap features, but this bug is messing up my example scene and making it hard to do some final testing.

**Comment by HungryProton** [comment] 2020-06-07 13:47
Yeah I noticed that an hour ago, the fix is almost ready

**Comment by HungryProton** [comment] 2020-06-07 14:11
I also noticed another issue with the noise preview and the dropdown in the math nodes. I'm working on fixing these too but the above fix should at least handle the main issue.

**Comment by BryceBubbles** [comment] 2020-06-08 03:57
I changed the noise preview code a fair bit so it now:
- Opens without the need to Replay Simulation.
- Shows the curve applied.
- Is Zoomed out by x8
- And Blend Noises shows the blended preview.

So yeah the bug you noticed might be gone?

**Comment by BryceBubbles** [comment] 2020-06-08 04:04
BTW the speed at which you replied and fixed this was very impressive!
Unfortunately I posted that comment and went to bed, as it was almost 2am here.

**Comment by HungryProton** [comment] 2020-06-08 09:11
I was working on the fix when I got the email notification. I'll merge your PR and see if the issue is still there.

**Comment by HungryProton** [comment] 2020-06-13 08:59
Closing the issue as every bugs described here seems fixed.

**Closed by HungryProton** 2020-06-13 08:59 UTC
